version: '3.4'

services:
  db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    expose:
      - "3306"

  rr_db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_DATABASE: rr_govwifi
    expose:
      - "3306"

  govuk-fake-registers:
    build:
      context: govuk_fake_register
    expose:
      - "7000"

  app:
    build:
      context: .
      args:
        BUNDLE_INSTALL_FLAGS: "${BUNDLE_INSTALL_FLAGS:- --jobs 20 --retry 5}"
    links:
      - db
      - rr_db
    expose:
    - "3000"
    depends_on:
      - 'govuk-fake-registers'
