default: &default
  end_user_docs_link: 'https://www.gov.uk/government/collections/connect-to-govwifi'
  end_user_troubleshooting_link: 'https://www.gov.uk/guidance/solve-problems-with-connecting-to-govwifi'
  organisation_docs_link: 'https://docs.wifi.service.gov.uk'
  support_link: 'https://www.wifi.service.gov.uk/support'
  connect_to_govwifi_link: 'https://www.wifi.service.gov.uk/about-govwifi/connect-to-govwifi'
  cookies_docs_link: 'https://www.wifi.service.gov.uk/cookies'
  product_page_link: 'https://wifi.service.gov.uk'
  organisation_register_url: 'https://government-organisation.register.gov.uk/records.json?page-size=5000'
  local_auth_register_url: 'https://local-authority-eng.register.gov.uk/records.json?page-size=5000'
  default_page_title: 'GovWifi admin'
  default_meta_description: 'GovWifi - Administration Platform'

development:
  <<: *default
  organisation_register_url: 'http://govuk-fake-registers:7000/organisation_records.json'
  local_auth_register_url: 'http://govuk-fake-registers:7000/local_auths_records.json'

test:
  <<: *default

staging:
  google_analytics_script_id: 'UA-127779891-2'

  <<: *default

production:
  google_analytics_script_id: 'UA-127779891-1'
  <<: *default
